xx <- read.csv("D:/DS/Project/gettingdata/ss06hid.csv", colClasses = "character")
head(xx)
colnames(x)
colnames(xx)
dim(xx)
download.file("https://d396qusza40orc.cloudfront.net/getdata/data/ss06hid.csv","D:/DS/Project/gettingdata/ss06hid.csv")
xx <- read.csv("D:/DS/Project/gettingdata/ss06hid.csv", colClasses = "character")
dim(xx)
df <- data.frame(xx)
properties <- subset(df, VAL==24)
dim(properties)
fes <- subset(df$FES)
fes <- subset(,df$FES)
fes <- df$FES
dim(fes)
length(fes)
head(fes)
download.file("https://d396qusza40orc.cloudfront.net/getdata/data/DATA.gov_NGAP.xlsx","D:/DS/Project/gettingdata/DATA.gov_NGAP.xlsx")
library(xlsx)
install.packages("xlsx")
library(xlsx)
dat <- read.xlsx("D:/DS/Project/gettingdata/DATA.gov_NGAP.xlsx",sheetIndex = 1, colIndex = 7:15, rowIndex = 18:23)
colind <- 7:15
rowind <- 18:23
dat <- read.xlsx("D:/DS/Project/gettingdata/DATA.gov_NGAP.xlsx",sheetIndex = 1, colIndex = colind, rowIndex = rowind)
system("java -version")
dat <- read.xlsx("D:/DS/Project/gettingdata/DATA.gov_NGAP.xlsx",sheetIndex = 1, colIndex = colind, rowIndex = rowind)
library(xlsx)
dat <- read.xlsx("D:/DS/Project/gettingdata/DATA.gov_NGAP.xlsx",sheetIndex = 1, colIndex = colind, rowIndex = rowind)
dat <- read.xlsx("D:/DS/Project/gettingdata/DATA.gov_NGAP.xlsx",sheetIndex = 1, colIndex = colind, rowIndex = rowind)
library(xlsx)
dat <- read.xlsx("D:/DS/Project/gettingdata/DATA.gov_NGAP.xlsx",sheetIndex = 1, colIndex = colind, rowIndex = rowind)
download.file("https://d396qusza40orc.cloudfront.net/getdata/data/DATA.gov_NGAP.xlsx","D:/DS/Project/gettingdata/DATA.gov_NGAP.xlsx",mode='wb')
dat <- read.xlsx("D:/DS/Project/gettingdata/DATA.gov_NGAP.xlsx",sheetIndex = 1, colIndex = colind, rowIndex = rowind)
sum(dat$Zip*dat$Ext,na.rm=T)
