---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r}
acts <- read.csv("D:/DS/Project/activity.csv", colClasses = "character")
acts$date <- as.Date(acts$date,"%Y-%m-%d")
acts$steps <- as.numeric(acts$steps)
actsnona <- na.omit(acts)
result <- tapply(actsnona$steps,as.factor(actsnona$date),sum)
dfres <- data.frame(result)
```

## What is mean total number of steps taken per day?

```{r}
hist(dfres$result)
summary(dfres)
```

## What is the average daily activity pattern?

```{r}
actsnona$interval <- sprintf("%06d",as.numeric(actsnona$interval))
datetime <- paste(actsnona$date,actsnona$interval)
h <- strptime(datetime,format='%Y-%m-%d %H%M%S')
actsnona$datetime <- h
AverageStepsPerDay <- tapply(actsnona$steps,as.factor(actsnona$interval),mean)
dfAvgSteps <- data.frame(AverageStepsPerDay )
actsnona$interval <- as.numeric(actsnona$interval)
fact <- as.factor(actsnona$interval)
fact <- levels(fact)
fact <- as.numeric(fact)
plot(fact, dfAvgSteps$AverageStepsPerDay, type = "l", ylab="AvergaStepsPerDay",xlab="TimeIntervals")
```
## Which interval contains maximum average steps
```{r}
which.max(dfAvgSteps$AverageStepsPerDay)
```

## Imputing missing values
# fill NAs
```{r}
h1 <- acts[,1]
sum(is.na(h1))
h <- is.na(h1)
indx <- which(h)
modh <- indx %% 288
idx288 <- modh==0
modh[idx288]=288
test <- AverageStepsPerDay[modh ]
h1[indx]=test
sum(is.na(h1))
newacts <- acts
newacts$steps <- h1
```
# make histogram
```{r}
newacts$date <- as.Date(newacts$date,"%Y-%m-%d")
newacts$steps <- as.numeric(newacts$steps)
result <- tapply(newacts$steps,as.factor(newacts$date),sum)
dfres <- data.frame(result)
hist(dfres$result)
```

# summary
```{r}
summary(dfres)
```

## Are there differences in activity patterns between weekdays and weekends?
```{r}
acts <- read.csv("D:/DS/Project/activity.csv", colClasses = "character")
acts$date <- as.Date(acts$date,"%Y-%m-%d")
acts$steps <- as.numeric(acts$steps)
actsnona <- na.omit(acts)
AverageStepsWeekdays <- tapply(actsnona$steps,as.factor(actsnona$interval),mean)
actsnona$date <- as.POSIXlt(actsnona$date)
actsnona$days <- weekdays(actsnona$date)
h <- actsnona$days=="Sunday" | actsnona$days=="Saturday"
WEidx <- which(h)
actsnona$days[WEidx]="weekend"
WDidx <- which(!h)
actsnona$days[WDidx]="weekday"
wedf <- subset(actsnona,actsnona$days=="weekend")
wddf <- subset(actsnona,actsnona$days=="weekday")
AverageStepsWeekDay <- tapply(wddf$steps,as.factor(wddf$interval),mean)
AverageStepsWeekend <- tapply(wedf$steps,as.factor(wedf$interval),mean)
dfresult <- data.frame(AverageStepsWeekDay)
dfwe <- data.frame(AverageStepsWeekend)
colnames(dfresult) <- c("avgSteps")
colnames(dfwe) <- c("avgSteps")
dfresult <- rbind(dfresult,dfwe)
daycol <- rep(c("weekday","weekend"),each=288)
dfdays <- data.frame(daycol)
dfresult <- cbind(dfresult,dfdays)
fact <- as.factor(actsnona$interval)
fact <- levels(fact)
fact <- as.numeric(fact)
dfinterval <- data.frame(fact)
dfinterval <- rbind(dfinterval,dfinterval)
dfresult <- cbind(dfresult,dfinterval)
library(lattice)
xyplot(dfresult$avgSteps~dfresult$fact|dfresult$daycol, data=dfresult ,pch=20)
str(fact)
```
